services:
  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend