#name: CI/CD
#
#on:
#  push:
#    branches: [main]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Build Docker images
#        run: |
#          docker build -f DockerfileProd -t my-app-prod .
#  test:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run tests
#        run: |
#          echo "Running tests (add pytest here later)"
#          echo "Tests passed"
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - uses: actions/checkout@v4
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - name: Deploy
#        run: |
#          flyctl scale count 1 --app help-me-understand --yes
#          flyctl deploy --app help-me-understand
#        env:
#          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}